remote/exporter: fix _stop call in USBSerialPortExport
This works the same way as ResourceExport.stop() does.

It fixes:
  TypeError: _stop() missing 1 required positional argument: 'start_params'

Signed-off-by: Bastian Krause <bst@pengutronix.de>