github: unit-tests: install system dependency libsnappy-dev
crossbar requires
autobahn[asyncio,compress,encryption,scram,serialization,twisted] which
requires python-snappy. Without libsnappy-dev the installation of
pythons-snappy fails with:

  snappy/snappymodule.cc:31:10: fatal error: snappy-c.h: No such file or directory

Signed-off-by: Bastian Krause <bst@pengutronix.de>